package main

import (
	"bytes"
	"compress/flate"
	"fmt"
	"go/format"
	"io"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"

	"github.com/HugoDaniel/wgslender/packages/go/wgslender"
)

// The generated file's first line. Go's convention for a file nobody should
// edit is a first line matching ^// Code generated .* DO NOT EDIT\.$, which
// diff tools, language servers and every "is this generated?" heuristic key
// off, so it is not free text. The command line goes inside it because the
// useful thing to know about a generated file is how to generate it again.
const headerFormat = "// Code generated by %q; DO NOT EDIT.\n\npackage %s\n\n"

// templateData is what the two templates below are rendered against.
type templateData struct {
	// Var is the identifier the shader is embedded as, Stream the unexported
	// one holding its compressed bytes.
	Var    string
	Stream string
	// Input is the shader this came from, in slash form so that the file reads
	// the same whichever platform generated it.
	Input string
	// The sizes, in bytes: the shader as written, minified, and compressed.
	// CompressedSize is zero unless it was compressed.
	OriginalSize   int
	MinifiedSize   int
	CompressedSize int
	// Quoted is the payload as a Go string literal — the minified shader, or
	// its DEFLATE stream.
	Quoted string
}

// plainTemplate embeds the shader as it is.
//
// A constant rather than a variable: it costs nothing at run time, nothing can
// assign over it, and it goes wherever a string literal goes.
var plainTemplate = template.Must(template.New("plain").Parse(
	`// {{.Var}} is {{.Input}}, minified from {{.OriginalSize}} bytes to {{.MinifiedSize}}.
const {{.Var}} = {{.Quoted}}
`))

// compressedTemplate embeds the shader as a DEFLATE stream.
//
// The stream is still a constant, so the binary carries it in read-only data
// and nothing is copied at start-up. What the constant cannot be is the shader
// itself, since inflating it is work: sync.OnceValue defers that until someone
// asks, and does it once however many goroutines ask at the same time.
var compressedTemplate = template.Must(template.New("compressed").Parse(
	`import (
	"compress/flate"
	"io"
	"strings"
	"sync"
)

// {{.Var}} returns {{.Input}}, minified from {{.OriginalSize}} bytes to {{.MinifiedSize}}
// and held here as a {{.CompressedSize}}-byte DEFLATE stream. It is inflated on
// the first call and kept.
var {{.Var}} = sync.OnceValue(func() string {
	// A flate reader holds nothing that needs closing, and a failure here would
	// mean the stream below had been edited.
	s, err := io.ReadAll(flate.NewReader(strings.NewReader({{.Stream}})))
	if err != nil {
		panic("wgslgen: decompressing {{.Var}}: " + err.Error())
	}
	return string(s)
})

// {{.Stream}} is {{.Var}}'s compressed bytes.
const {{.Stream}} = {{.Quoted}}
`))

// render builds the Go file for one minified shader, followed by whatever
// -module had to say about it.
//
// The order is not a preference. The compressed form opens with an import
// block, and Go wants every import directly after the package clause, so the
// shader has to come first.
func render(cfg config, m wgslender.MinifyResult, decls []byte) ([]byte, error) {
	data := templateData{
		Var:          cfg.varName,
		Stream:       unexport(cfg.varName) + "Deflate",
		Input:        filepath.ToSlash(cfg.input),
		OriginalSize: m.OriginalSize,
		MinifiedSize: m.MinifiedSize,
		Quoted:       strconv.Quote(m.Code),
	}
	tmpl := plainTemplate
	if cfg.compress {
		stream, err := deflate(m.Code)
		if err != nil {
			return nil, fmt.Errorf("compressing %s: %w", cfg.input, err)
		}
		data.CompressedSize = len(stream)
		data.Quoted = strconv.Quote(stream)
		tmpl = compressedTemplate
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, headerFormat, "wgslgen "+strings.Join(cfg.args, " "), cfg.pkgName)
	if err := tmpl.Execute(&b, data); err != nil {
		return nil, fmt.Errorf("rendering the generated file, which is a bug in wgslgen: %w", err)
	}
	b.Write(decls)
	return formatGo(b.Bytes())
}

// proofPath is where the layout proof for out goes: beside it, named the way Go
// names a test file. An extension other than .go keeps its own, so that a
// generated pair can be pinned as testdata under a name go build ignores.
func proofPath(out string) string {
	ext := filepath.Ext(out)
	return strings.TrimSuffix(out, ext) + "_test" + ext
}

// formatGo runs the generated text through go/format, so that a package using
// this tool does not need a gofmt pass after every go:generate. It is also the
// check that the templates produced Go at all.
func formatGo(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("the generated file is not valid Go, which is a bug in wgslgen: %w", err)
	}
	return out, nil
}

// deflate compresses the shader.
//
// A raw DEFLATE stream rather than gzip: the generated file already records the
// sizes and the file name, which is most of what a gzip header would carry, and
// compress/flate is what reads it back.
func deflate(s string) (string, error) {
	var b strings.Builder
	w, err := flate.NewWriter(&b, flate.BestCompression)
	if err != nil {
		return "", err
	}
	if _, err := io.WriteString(w, s); err != nil {
		return "", err
	}
	if err := w.Close(); err != nil {
		return "", err
	}
	return b.String(), nil
}

// unexport lowercases a name's first letter, which is what keeps the stream
// constant out of the package's public surface.
func unexport(name string) string {
	r, size := utf8.DecodeRuneInString(name)
	return string(unicode.ToLower(r)) + name[size:]
}
