//! Turning what a shader declares into Rust: constants for the slots, structs
//! for the buffers, and a proof that the structs are laid out the way the GPU
//! will read them.
//!
//! The proof is the point. A generated struct is a claim about memory — that
//! `Params` is sixteen bytes with `time` at offset eight — and a claim nobody
//! checks is a silent wrong-pixels bug at run time. Every struct here comes
//! with a `const _: ()` block asserting its own size, alignment and field
//! offsets against the numbers the library computed, so a mis-mapping is a
//! failed build in the crate that asked for it.
//!
//! What cannot be proved is not generated: a padded matrix column or array
//! stride has no Rust equivalent, and this refuses those by name rather than
//! guessing.

use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::{Ident, LitStr, Token, parenthesized, token};
use wgslender_core::{Binding, EntryPoint, Reflection, StructLayout, TypeInfo, reflect};

use crate::expand;
use crate::parse::{Bytemuck, Embedding, Invocation};

/// One `wgsl_module!` invocation, parsed.
///
/// The header — `pub demo,` — is this macro's own; everything after it is the
/// argument list [`Invocation`] already knows how to read.
pub(crate) struct Module {
    /// How visible the generated module is.
    vis: Vis,
    /// What the generated module is called.
    name: Ident,
    /// The shader and what to do with it.
    invocation: Invocation,
}

impl Parse for Module {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let vis = input.parse()?;
        let name = input.parse()?;
        input.parse::<Token![,]>()?;
        let invocation = Invocation::parse(input, Embedding::Module)?;
        Ok(Self {
            vis,
            name,
            invocation,
        })
    }
}

/// The `pub` in front of the module's name, if the caller wrote one.
///
/// `syn::Visibility` would parse this, but it lives behind syn's `derive`
/// feature — the derive machinery this crate has no use for. The grammar is
/// `pub`, optionally followed by a parenthesised restriction, so it is kept
/// here: the caller's own tokens, handed straight back with their spans, which
/// is what makes a mistake in `pub(whatever)` point at what they wrote.
struct Vis(TokenStream);

impl Parse for Vis {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        if !input.peek(Token![pub]) {
            return Ok(Self(TokenStream::new()));
        }
        let keyword: Token![pub] = input.parse()?;
        let mut tokens = quote! { #keyword };
        if input.peek(token::Paren) {
            let restriction;
            parenthesized!(restriction in input);
            let restriction: TokenStream = restriction.parse()?;
            tokens.extend(quote! { (#restriction) });
        }
        Ok(Self(tokens))
    }
}

impl quote::ToTokens for Vis {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        self.0.to_tokens(tokens);
    }
}

/// The whole macro, as a module.
pub(crate) fn expand(module: &Module) -> syn::Result<TokenStream> {
    let path = &module.invocation.path;
    let prepared = expand::prepare(&module.invocation)?;

    // Reflection reads the file as written: the names a host program binds
    // against are the ones in the source, not the ones minification produced.
    let reflection =
        reflect(&prepared.source).map_err(|err| expand::library_failed(path, "reflect", &err))?;
    if !reflection.errors.is_empty() {
        return Err(syn::Error::new_spanned(
            path,
            format!(
                "{} did not parse, so there is nothing to generate from it:\n{}",
                path.value(),
                reflection.errors.join("\n"),
            ),
        ));
    }

    let bindings = bindings(path, &reflection.bindings)?;
    let structs = structs(path, &reflection, module.invocation.bytemuck)?;
    let entry_points = entry_points(path, &reflection.entry_points)?;

    let vis = &module.vis;
    let name = &module.name;
    let doc = format!(
        "What `{}` declares, as Rust.\n\nGenerated by `wgsl_module!`.",
        path.value(),
    );
    let source = &prepared.text;
    let tracked = &prepared.tracked;

    Ok(quote! {
        #[doc = #doc]
        // This lands in someone else's crate, under someone else's lints. A
        // private module's `pub` items and the `_padN` fields are both this
        // macro's doing, and neither is anything the author can act on.
        #[allow(unreachable_pub, clippy::pub_underscore_fields)]
        #vis mod #name {
            // Nothing reads this constant. It exists so that the compiler
            // records a dependency on the shader, and editing the shader
            // rebuilds whatever generated from it.
            const _: &[u8] = ::core::include_bytes!(#tracked);

            /// The shader itself, as this macro embedded it.
            pub const SOURCE: &str = #source;

            #bindings
            #structs
            #entry_points
        }
    })
}

/// One `pub const` per resource, in a module of their own.
fn bindings(path: &LitStr, bindings: &[Binding]) -> syn::Result<TokenStream> {
    let mut taken: Vec<String> = Vec::new();
    let mut slots = Vec::new();

    for binding in bindings {
        let name = screaming_ident(&binding.name, path, "binding")?;
        reject_duplicate(path, &mut taken, &name, &binding.name)?;

        let doc = format!(
            "`{}`, a `{}` at `@group({}) @binding({})`.",
            binding.name, binding.ty, binding.group, binding.binding,
        );
        let group = Literal::u32_unsuffixed(binding.group);
        let slot = Literal::u32_unsuffixed(binding.binding);
        slots.push(quote! {
            #[doc = #doc]
            pub const #name: ::wgslender::BindingSlot =
                ::wgslender::BindingSlot { group: #group, binding: #slot };
        });
    }

    Ok(quote! {
        /// Where each of the shader's resources is bound.
        pub mod bindings {
            #(#slots)*
        }
    })
}

/// One `pub const` per entry point, plus its workgroup size where it has one.
fn entry_points(path: &LitStr, entry_points: &[EntryPoint]) -> syn::Result<TokenStream> {
    let mut taken: Vec<String> = Vec::new();
    let mut consts = Vec::new();

    for entry in entry_points {
        let name = screaming_ident(&format!("entry_{}", entry.name), path, "entry point")?;
        reject_duplicate(path, &mut taken, &name, &entry.name)?;

        let stage = entry.stage.as_str();
        let doc = format!("`{}`, the shader's {} entry point.", entry.name, stage);
        let text = &entry.name;
        consts.push(quote! {
            #[doc = #doc]
            pub const #name: &str = #text;
        });

        let Some([x, y, z]) = entry.workgroup_size else {
            continue;
        };
        let size = format_ident!("{}_WORKGROUP_SIZE", name);
        let doc = format!("The `@workgroup_size` `{}` is declared with.", entry.name);
        let (x, y, z) = (
            Literal::u32_unsuffixed(x),
            Literal::u32_unsuffixed(y),
            Literal::u32_unsuffixed(z),
        );
        consts.push(quote! {
            #[doc = #doc]
            pub const #size: [u32; 3] = [#x, #y, #z];
        });
    }

    Ok(quote! { #(#consts)* })
}

/// One Rust struct per host-shareable struct the shader declares.
fn structs(path: &LitStr, reflection: &Reflection, bytemuck: Bytemuck) -> syn::Result<TokenStream> {
    let mut generated = Vec::new();
    for (name, layout) in &reflection.structs {
        generated.push(one_struct(path, name, layout, bytemuck)?);
    }
    Ok(quote! { #(#generated)* })
}

/// A struct, a constructor for it, and the proof that it is laid out right.
fn one_struct(
    path: &LitStr,
    name: &str,
    layout: &StructLayout,
    bytemuck: Bytemuck,
) -> syn::Result<TokenStream> {
    let ident = type_ident(name, path, "struct")?;
    let mut members = Members::default();

    for field in &layout.fields {
        let context = Context {
            path,
            owner: name,
            field: &field.name,
            spelling: &field.ty,
        };
        let Some(info) = field.type_info.as_ref() else {
            return Err(context
                .refuse("the library did not report a type for it, so there is nothing to map"));
        };
        let member = type_ident(&field.name, path, "field")?;

        match mapping(info, &context)? {
            Mapping::Tail => {
                let constant = screaming_ident(&format!("{}_offset", field.name), path, "field")?;
                members.tail(&constant, field.offset, &context);
            }
            Mapping::Value { ty, size } => {
                members.pad_to(field.offset);
                let doc = format!(
                    "`{}: {}` — {} bytes at offset {}.",
                    field.name, field.ty, size, field.offset,
                );
                members.place(&ident, &member, &ty, size, field.offset, &doc);
            }
        }
    }
    members.pad_to(layout.size);

    let Members {
        fields,
        arguments,
        initialisers,
        assertions,
        offsets,
        ..
    } = members;

    let alignment = Literal::u32_unsuffixed(layout.alignment);
    let size = Literal::u32_unsuffixed(layout.size);
    let doc = format!(
        "`struct {name}` — {} bytes, aligned to {}.",
        layout.size, layout.alignment,
    );
    let derives = match bytemuck {
        Bytemuck::Derive => quote! { #[derive(::bytemuck::Pod, ::bytemuck::Zeroable)] },
        Bytemuck::Skip => quote! {},
    };
    let new_doc = format!(
        "A `{name}` with these fields and its padding zeroed.\n\n\
         The padding is not an argument: it is the shader's layout, not data.",
    );
    let size_message = format!(
        "wgsl_module!: `{name}` is not the {} bytes the shader's layout requires",
        layout.size,
    );
    let alignment_message = format!(
        "wgsl_module!: `{name}` is not aligned to the {} bytes the shader's layout requires",
        layout.alignment,
    );

    Ok(quote! {
        #[doc = #doc]
        #[repr(C, align(#alignment))]
        #[derive(Clone, Copy, Debug)]
        #derives
        pub struct #ident {
            #(#fields)*
        }

        impl #ident {
            #(#offsets)*

            #[doc = #new_doc]
            #[allow(clippy::too_many_arguments)]
            pub const fn new(#(#arguments)*) -> Self {
                Self { #(#initialisers)* }
            }
        }

        // The generated struct proves its own layout. If any of this is false,
        // the crate that asked for the module fails to build — which is the
        // only moment at which a layout mistake is still cheap.
        const _: () = {
            assert!(::core::mem::size_of::<#ident>() == #size, #size_message);
            assert!(::core::mem::align_of::<#ident>() == #alignment, #alignment_message);
            #(#assertions)*
        };
    })
}

/// The pieces of a struct, accumulated field by field.
#[derive(Default)]
struct Members {
    /// Field declarations, padding included.
    fields: Vec<TokenStream>,
    /// `new`'s parameter list, padding excluded.
    arguments: Vec<TokenStream>,
    /// The struct literal `new` builds.
    initialisers: Vec<TokenStream>,
    /// One `offset_of!` assertion per placed field.
    assertions: Vec<TokenStream>,
    /// Associated constants for the fields that have no Rust type.
    offsets: Vec<TokenStream>,
    /// How far into the struct the fields so far reach.
    cursor: u32,
    /// How many padding fields have been emitted.
    pads: u32,
}

impl Members {
    /// Fills the gap between the last field and `offset` with explicit padding.
    ///
    /// Explicit, rather than left to the compiler, because implicit padding is
    /// what makes a struct not [`Pod`](https://docs.rs/bytemuck): a byte the
    /// caller cannot account for is a byte that cannot be sent to the GPU
    /// wholesale.
    fn pad_to(&mut self, offset: u32) {
        let Some(gap) = offset.checked_sub(self.cursor).filter(|gap| *gap > 0) else {
            return;
        };
        let name = format_ident!("_pad{}", self.pads);
        let bytes = Literal::u32_unsuffixed(gap);
        let doc = format!(
            "{gap} bytes of padding: the shader's layout puts the next field at offset {offset}.",
        );
        self.fields.push(quote! {
            #[doc = #doc]
            pub #name: [u8; #bytes],
        });
        self.initialisers.push(quote! { #name: [0; #bytes], });
        self.cursor = offset;
        self.pads += 1;
    }

    /// Adds a field with a Rust type, and the assertion that it lands right.
    fn place(
        &mut self,
        owner: &Ident,
        name: &Ident,
        ty: &TokenStream,
        size: u32,
        offset: u32,
        doc: &str,
    ) {
        let message = format!(
            "wgsl_module!: `{owner}::{name}` is not at the offset {offset} the shader's layout requires",
        );
        let at = Literal::u32_unsuffixed(offset);
        self.fields.push(quote! {
            #[doc = #doc]
            pub #name: #ty,
        });
        self.arguments.push(quote! { #name: #ty, });
        self.initialisers.push(quote! { #name, });
        self.assertions.push(quote! {
            assert!(::core::mem::offset_of!(#owner, #name) == #at, #message);
        });
        self.cursor = offset + size;
    }

    /// Records a runtime-sized array as the offset it begins at.
    ///
    /// It gets no field: how many elements follow is not known until the host
    /// allocates the buffer, and a Rust struct cannot end in a length it does
    /// not know.
    fn tail(&mut self, constant: &Ident, offset: u32, context: &Context<'_>) {
        let at = Literal::u32_unsuffixed(offset);
        let doc = format!(
            "Where `{}: {}` begins — {offset} bytes in.\n\n\
             It is runtime-sized, so it is an offset rather than a field: write \
             the elements past this point yourself.",
            context.field, context.spelling,
        );
        self.offsets.push(quote! {
            #[doc = #doc]
            pub const #constant: u32 = #at;
        });
    }
}

/// Which field is being mapped, for the message when it cannot be.
struct Context<'a> {
    /// The path literal every error points at.
    path: &'a LitStr,
    /// The struct the field belongs to.
    owner: &'a str,
    /// The field's name.
    field: &'a str,
    /// The field's type, as the shader spells it.
    spelling: &'a str,
}

impl Context<'_> {
    /// This field cannot be generated, and why.
    fn refuse(&self, why: &str) -> syn::Error {
        syn::Error::new_spanned(
            self.path,
            format!(
                "cannot generate a Rust field for `{}.{}` (`{}`): {why}",
                self.owner, self.field, self.spelling,
            ),
        )
    }

    /// A type this macro has no mapping for.
    fn unmapped(&self, what: &str) -> syn::Error {
        self.refuse(&format!(
            "`{what}` is not a type this macro maps (v1)\n\
             it generates f32, u32 and i32, vectors and matrices of them, fixed-size arrays, \
             nested structs, and atomics of any of those",
        ))
    }
}

/// What a WGSL type becomes in Rust.
enum Mapping {
    /// A type, and the bytes it occupies.
    Value {
        /// The Rust type.
        ty: TokenStream,
        /// Its size, which must be the shader's.
        size: u32,
    },
    /// A runtime-sized array, which becomes an offset rather than a field.
    Tail,
}

/// The Rust equivalent of a WGSL type, or a refusal naming the field.
fn mapping(info: &TypeInfo, context: &Context<'_>) -> syn::Result<Mapping> {
    match info {
        TypeInfo::Scalar { name, size, .. } => {
            let ty = match name.as_str() {
                "f32" => quote! { f32 },
                "u32" => quote! { u32 },
                "i32" => quote! { i32 },
                other => return Err(context.unmapped(other)),
            };
            Ok(Mapping::Value { ty, size: *size })
        }
        TypeInfo::Vec {
            width,
            format,
            size,
            ..
        } => {
            let (component, _) = value(format, context)?;
            let width = Literal::u8_unsuffixed(*width);
            Ok(Mapping::Value {
                ty: quote! { [#component; #width] },
                size: *size,
            })
        }
        TypeInfo::Mat {
            cols,
            rows,
            format,
            size,
            stride,
            ..
        } => {
            let (component, component_size) = value(format, context)?;
            let column = u32::from(*rows) * component_size;
            if column != *stride {
                return Err(context.refuse(&format!(
                    "{cols} columns of {column} bytes, {stride} bytes apart — a padded column \
                     stride has no Rust equivalent, and this macro will not guess (v1)\n\
                     it generates the matrices whose column stride is their column size: \
                     mat2x2f, mat4x2f, mat2x4f, mat4x4f and the like",
                )));
            }
            let rows = Literal::u8_unsuffixed(*rows);
            let cols = Literal::u8_unsuffixed(*cols);
            Ok(Mapping::Value {
                ty: quote! { [[#component; #rows]; #cols] },
                size: *size,
            })
        }
        TypeInfo::Array {
            format,
            count,
            size,
            stride,
            ..
        } => {
            let (Some(count), Some(size)) = (count, size) else {
                return Ok(Mapping::Tail);
            };
            let (element, element_size) = value(format, context)?;
            if element_size != *stride {
                return Err(context.refuse(&format!(
                    "{count} elements of {element_size} bytes, {stride} bytes apart — a padded \
                     element stride has no Rust equivalent, and this macro will not guess (v1)\n\
                     it generates the arrays whose stride is their element size",
                )));
            }
            let count = Literal::u32_unsuffixed(*count);
            Ok(Mapping::Value {
                ty: quote! { [#element; #count] },
                size: *size,
            })
        }
        TypeInfo::Struct { name, size, .. } => {
            let ident = type_ident(name, context.path, "struct")?;
            Ok(Mapping::Value {
                ty: quote! { #ident },
                size: *size,
            })
        }
        // An atomic occupies exactly what it makes atomic, and the atomicity is
        // the GPU's business: the host writes the initial value like any other.
        TypeInfo::Atomic { format, .. } => {
            value(format, context).map(|(ty, size)| Mapping::Value { ty, size })
        }
        _ => Err(context.unmapped(context.spelling)),
    }
}

/// [`mapping`], where a runtime-sized array would make no sense.
fn value(info: &TypeInfo, context: &Context<'_>) -> syn::Result<(TokenStream, u32)> {
    match mapping(info, context)? {
        Mapping::Value { ty, size } => Ok((ty, size)),
        Mapping::Tail => Err(context.refuse(
            "a runtime-sized array is inside something, where WGSL only allows one as the last \
             member of a struct",
        )),
    }
}

/// A name as a Rust identifier, raw where WGSL allows what Rust reserves.
///
/// A WGSL field called `type` or `in` is perfectly ordinary, and `r#type` is
/// what Rust calls the same thing. The four keywords that cannot be written raw
/// have nowhere left to go, and say so.
fn type_ident(name: &str, path: &LitStr, what: &str) -> syn::Result<Ident> {
    if let Ok(ident) = syn::parse_str::<Ident>(name) {
        return Ok(ident);
    }
    if let Ok(ident) = syn::parse_str::<Ident>(&format!("r#{name}")) {
        return Ok(ident);
    }
    Err(syn::Error::new_spanned(
        path,
        format!(
            "the {what} `{name}` cannot be spelled in Rust: `{name}` is one of the few keywords \
             that has no raw form (v1)",
        ),
    ))
}

/// A name as a Rust constant is spelled: `params` becomes `PARAMS`.
fn screaming_ident(name: &str, path: &LitStr, what: &str) -> syn::Result<Ident> {
    let shouted = name.to_uppercase();
    match syn::parse_str::<Ident>(&shouted) {
        Ok(ident) => Ok(ident),
        Err(_) => Err(syn::Error::new_spanned(
            path,
            format!("the {what} `{name}` does not name a Rust constant (as `{shouted}`)"),
        )),
    }
}

/// Two names that shout the same would generate the same constant twice, and
/// the compiler's complaint about that would be about a name the author never
/// wrote.
fn reject_duplicate(
    path: &LitStr,
    taken: &mut Vec<String>,
    ident: &Ident,
    source_name: &str,
) -> syn::Result<()> {
    let shouted = ident.to_string();
    if taken.contains(&shouted) {
        return Err(syn::Error::new_spanned(
            path,
            format!(
                "`{source_name}` and something before it both come out as `{shouted}`, and one \
                 module cannot hold two constants of that name",
            ),
        ));
    }
    taken.push(shouted);
    Ok(())
}

#[cfg(test)]
mod tests {
    use proc_macro2::Span;
    use quote::quote;
    use syn::LitStr;

    use super::{Module, expand, screaming_ident, type_ident};

    fn path() -> LitStr {
        LitStr::new("shader.wgsl", Span::call_site())
    }

    fn expanded(invocation: proc_macro2::TokenStream) -> String {
        let module = match syn::parse2::<Module>(invocation) {
            Ok(module) => module,
            Err(err) => panic!("the invocation did not parse: {err}"),
        };
        match expand(&module) {
            Ok(tokens) => tokens.to_string(),
            Err(err) => panic!("the invocation did not expand: {err}"),
        }
    }

    /// The layout proofs are the reason to trust the generated structs, and
    /// they are also the part of the expansion nothing else would miss: a
    /// generator that quietly stopped emitting them would pass every test that
    /// only reads the struct back. So they are pinned where they are written.
    #[test]
    #[cfg(not(miri))]
    fn the_expansion_proves_its_own_layout() {
        let tokens = expanded(quote! { pub uniforms, "wgsl/uniforms.wgsl" });
        for fragment in ["size_of", "align_of", "offset_of", "resolution", "time"] {
            assert!(
                tokens.contains(fragment),
                "no {fragment} assertion in: {tokens}"
            );
        }
    }

    /// Everything else the expansion is made of, in one pass: the rebuild
    /// tracking, the shader, the slots, the entry point, and the padding that
    /// keeps the struct free of holes the caller cannot account for.
    #[test]
    #[cfg(not(miri))]
    fn the_expansion_carries_what_a_host_program_binds_against() {
        let tokens = expanded(quote! { pub uniforms, "wgsl/uniforms.wgsl" });
        for fragment in [
            "include_bytes",
            "SOURCE",
            "mod bindings",
            "BindingSlot",
            "PARAMS",
            "DATA",
            "ENTRY_MAIN",
            "ENTRY_MAIN_WORKGROUP_SIZE",
            "_pad0",
        ] {
            assert!(tokens.contains(fragment), "no {fragment} in: {tokens}");
        }
    }

    #[test]
    fn an_ordinary_name_stays_itself() {
        let Ok(ident) = type_ident("resolution", &path(), "field") else {
            panic!("an ordinary name must map")
        };
        assert_eq!(ident.to_string(), "resolution");
    }

    /// `in`, `type` and `move` are WGSL identifiers like any other. Rust has
    /// raw identifiers for exactly this.
    #[test]
    fn a_rust_keyword_becomes_a_raw_identifier() {
        for name in ["move", "type", "in", "match", "ref"] {
            let Ok(ident) = type_ident(name, &path(), "field") else {
                panic!("`{name}` must map to a raw identifier")
            };
            assert_eq!(ident.to_string(), format!("r#{name}"));
        }
    }

    #[test]
    fn the_keywords_with_no_raw_form_are_refused() {
        for name in ["crate", "self", "super", "Self"] {
            assert!(
                type_ident(name, &path(), "field").is_err(),
                "`{name}` has no raw form and must be refused"
            );
        }
    }

    #[test]
    fn a_constant_is_shouted() {
        let Ok(ident) = screaming_ident("params", &path(), "binding") else {
            panic!("a binding name must map")
        };
        assert_eq!(ident.to_string(), "PARAMS");
    }
}
